export const IPC_CONTRACT_VERSION = 4 as const

export const QUIETDESK_CHANNELS = {
  bootstrap: 'quietdesk:v2:bootstrap',
  widgetSnapshot: 'quietdesk:v2:widget:snapshot',
  daySnapshot: 'quietdesk:v2:library:day',
  dailyLog: 'quietdesk:v4:daily-logs:get',
  saveDailyLogManual: 'quietdesk:v4:daily-logs:save-manual',
  exportDailyLog: 'quietdesk:v4:daily-logs:export',
  getEntity: 'quietdesk:v2:entities:get',
  getHistory: 'quietdesk:v2:entities:history',
  listTrash: 'quietdesk:v2:entities:trash-list',
  createTask: 'quietdesk:v2:tasks:create',
  updateTask: 'quietdesk:v2:tasks:update',
  setTaskCompletion: 'quietdesk:v2:tasks:set-completion',
  rescheduleTask: 'quietdesk:v2:tasks:reschedule',
  createNote: 'quietdesk:v2:notes:create',
  getNote: 'quietdesk:v2:notes:get',
  updateNote: 'quietdesk:v2:notes:update',
  createSchedule: 'quietdesk:v2:schedules:create',
  updateSchedule: 'quietdesk:v2:schedules:update',
  getDraft: 'quietdesk:v2:drafts:get',
  saveDraft: 'quietdesk:v2:drafts:save',
  submitDraft: 'quietdesk:v3:drafts:submit',
  trashEntity: 'quietdesk:v2:entities:trash',
  restoreEntity: 'quietdesk:v2:entities:restore',
  permanentlyDeleteEntity: 'quietdesk:v2:entities:permanent-delete',
  updateAppearance: 'quietdesk:v2:settings:appearance',
  getShortcut: 'quietdesk:v3:shortcuts:get',
  updateShortcut: 'quietdesk:v3:shortcuts:update',
  openExternal: 'quietdesk:v3:links:open-external',
  showWindow: 'quietdesk:v2:windows:show',
  hideWindow: 'quietdesk:v2:windows:hide',
  windowContext: 'quietdesk:v2:windows:context',
  changed: 'quietdesk:v2:changed'
} as const
